# Generated by Django 3.2.6 on 2021-08-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('help_text', models.CharField(blank=True, max_length=2000)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('type', models.CharField(choices=[('percentage', 'Percentage')], default='percentage', max_length=255)),
            ],
        ),
    ]
